# Generated by Django 5.1.7 on 2025-04-15 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon code for the badge', max_length=20)),
                ('category', models.CharField(choices=[('organizer', 'Organizer Badge'), ('participant', 'Participant Badge'), ('helper', 'Helper Badge')], max_length=20)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')])),
                ('requirement_count', models.IntegerField(help_text='Number of actions required to earn this badge')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_progress', to=settings.AUTH_USER_MODEL)),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badgetype')),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badgetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
