# Generated by Django 5.1.7 on 2025-04-21 16:01

from django.db import migrations


def update_superusers(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    for superuser in CustomUser.objects.filter(is_superuser=True):
        superuser.user_type = 'manager'
        superuser.is_account_confirmed = True
        superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_created_at_remove_profile_updated_at_and_more'),
    ]

    operations = [
    ]
