# Generated by Django 5.1.7 on 2025-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_is_cancelled_event_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_for',
            field=models.CharField(choices=[('student_only', 'Student Only'), ('everyone', 'Everyone')], default='everyone', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='physical', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='teacher', max_length=50),
        ),
    ]
