# Generated by Django 5.1.7 on 2025-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_for_event_event_type_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_for',
            field=models.CharField(choices=[('student_only', 'Student Only'), ('teacher_only', 'Teacher Only'), ('everyone', 'Everyone')], default='everyone', max_length=50),
        ),
    ]
