# Generated by Django 5.1.7 on 2025-03-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_event_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_for',
            field=models.CharField(choices=[('student_only', 'Student Only'), ('teacher_only', 'Teacher Only'), ('everyone', 'Everyone')], default='student_only', max_length=50),
        ),
    ]
