# Generated by Django 5.1.7 on 2025-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_max_attendees_alter_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
