# Generated by Django 5.1.7 on 2025-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
